Added exercises for Typing React State
bitovi/trainings pull request #21
Opened 2023-10-01 23:54 UTC by avinavdixit25

2023-10-04 18:06 UTC, chasenlehara commented
Adding the links here so this is easier to review:


**Exercise 1**

- [Problem](https://codesandbox.io/s/github/bitovi/trainings/tree/typing-react-state/typing-react-state/Exercise1/problem?file=/App.tsx)
- [Solution](https://codesandbox.io/s/github/bitovi/trainings/tree/typing-react-state/typing-react-state/Exercise1/solution?file=/App.tsx)

**Exercise 2**

- [Problem](https://codesandbox.io/s/github/bitovi/trainings/tree/typing-react-state/typing-react-state/Exercise2/problem?file=/App.tsx)
- [Solution](https://codesandbox.io/s/github/bitovi/trainings/tree/typing-react-state/typing-react-state/Exercise2/solution?file=/App.tsx)

**Exercise 3**

- [Problem](https://codesandbox.io/s/github/bitovi/trainings/tree/typing-react-state/typing-react-state/Exercise3/problem?file=/App.tsx)
- [Solution](https://codesandbox.io/s/github/bitovi/trainings/tree/typing-react-state/typing-react-state/Exercise3/solution?file=/App.tsx)

2023-10-04 20:02 UTC, chasenlehara requested changes
It would be good to have all the necessary setup to run these locally so we can easily develop them without relying on CodeSandbox.

Please feel free to merge in as-is, or make changes in this branch and then merge it in.

2023-10-04 20:02 UTC, chasenlehara commented on typing-react-state/Exercise1/problem/.codesandbox/template.json
> +    "React"
These can be `["react", "typescript"]`

2023-10-04 20:02 UTC, chasenlehara commented on typing-react-state/Exercise1/problem/package.json
> +    "react-scripts": "4.0.0"
Instead of “pinning” the versions here, we should have the normal `^` semver range and commit the `package-lock.json` file.

2023-10-04 20:02 UTC, chasenlehara commented on typing-react-state/Exercise1/solution/App.tsx
> +      <section>Company Name: {companyName}</section>
These should be `p` elements.

2023-10-04 20:02 UTC, chasenlehara commented on typing-react-state/Exercise1/solution/App.tsx
> +        </div>
I think this `div` can be removed.

2023-10-04 20:02 UTC, chasenlehara commented on typing-react-state/Exercise1/solution/App.tsx
> +          <div> Owner: {companyDetails.owner || " Not Known"} </div>
These should be `p` elements.

2023-10-04 20:02 UTC, chasenlehara commented on typing-react-state/Exercise1/solution/App.tsx
> +          {/* Property 'departments' does not exist on type '{}'. */}
Is this supposed to be here?

2023-10-04 20:02 UTC, chasenlehara commented on typing-react-state/Exercise1/solution/App.tsx
> +          employees?.map((employee) => <div key={employee}>{employee}</div>)
These should be `li` elements wrapped in an `ol` or `ul`.

2023-10-04 20:02 UTC, chasenlehara commented on typing-react-state/Exercise1/solution/App.tsx
> +          <div>No employees</div>
This should be `p` element.

2023-10-04 20:02 UTC, chasenlehara commented on typing-react-state/Exercise1/solution/App.tsx
> +        </div>
Does this `div` do anything?

2023-10-04 20:02 UTC, chasenlehara commented on typing-react-state/Exercise2/problem/App.tsx
> +//      have to be deleted entirely.
For all of these prompts, we may want to number them so the “minimum” we want them to do is more clear.

Example: https://github.com/bitovi/trainings/blob/299ff9d94a05206698d11061be9bc98e20c8f137/intro-to-accessibility-first/buttons-and-links/problem/index.html#L4-L9

2023-10-04 20:02 UTC, chasenlehara commented on typing-react-state/Exercise2/solution/App.tsx
> +  }
We should move this out of `App`’s scope, right?

2023-10-04 20:02 UTC, chasenlehara commented on typing-react-state/Exercise3/solution/App.tsx
> +    // Cannot assign to 'current' because it is a read-only property.
Ah, I think I understand these now. I think it’s safe to remove these from both the problem and solution, since CodeSandbox will show these errors.

2023-10-04 20:02 UTC, chasenlehara commented on typing-react-state/Exercise3/solution/App.tsx
> +      </div>
These inputs should be wrapped in `label` elements.

2023-10-05 22:35 UTC, CMLabay commented on typing-react-state/Exercise1/problem/App.tsx
> +import React, { useState, useEffect } from "react";
remove React import

2023-10-05 22:36 UTC, CMLabay commented on typing-react-state/Exercise1/solution/App.tsx
> +interface CompanyDetailProps {
CompanyDetails

2023-10-05 22:37 UTC, CMLabay commented on typing-react-state/Exercise1/solution/App.tsx
> +    size: 0,
make a variable for initial details

2023-10-05 22:57 UTC, CMLabay commented on typing-react-state/Exercise2/problem/App.tsx
> +//    - TypeScript will complain about the “type” property
reword this to be less specific

2023-10-05 23:09 UTC, CMLabay commented on typing-react-state/Exercise3/problem/App.tsx
> +// instead of useRef?
what if similar to slide ex useref to give focus to first input that has an error?

2023-10-06 02:25 UTC, chasenlehara commented
I’m going to merge this in as-is. @CMLabay and I will work through our review comments.

2023-10-06 02:26 UTC, merged